repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: bundle.js|bundle.js.map|bundle.css
      - id: end-of-file-fixer
        exclude: bundle.js|bundle.js.map|bundle.css
      - id: check-builtin-literals
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: file-contents-sorter
        args: ["--ignore-case", "--unique"]
        exclude: .gitignore|.dockerignore|requirements[-\w]*.txt
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.11"
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-django
        args: ["--lint", "--reformat"]
